
#ifndef PLAYLISTDEFS_H
#define PLAYLISTDEFS_H

#define PLAYLIST_MENUS 0
#define PLAYLIST_CALM 1
#define PLAYLIST_ACTION 2
#define PLAYLIST_FAILURE 3
#define PLAYLIST_SUCCESS 4
#define PLAYLIST_INTRO 5
#define PLAYLIST_CREDITS 6

#define PLAYLIST_AMOUNT 7

extern const char *playlistNames[PLAYLIST_AMOUNT];

#endif


