
#ifndef PHYSICS_COLLISIONGROUPS_H
#define PHYSICS_COLLISIONGROUPS_H

#define PHYSICS_COLLISIONGROUP_STATIC 0
#define PHYSICS_COLLISIONGROUP_MODEL_PARTICLES_WO_UNIT_COLL 1
#define PHYSICS_COLLISIONGROUP_MODEL_PARTICLES 2
#define PHYSICS_COLLISIONGROUP_MODEL_PARTICLES_WO_UNIT_COLL_NO_SOUND 3
#define PHYSICS_COLLISIONGROUP_MODEL_PARTICLES_NO_SOUND 4
#define PHYSICS_COLLISIONGROUP_UNITS 5
#define PHYSICS_COLLISIONGROUP_DOORS 6
#define PHYSICS_COLLISIONGROUP_DYNAMIC_TERRAINOBJECTS 7
#define PHYSICS_COLLISIONGROUP_FLUID_CONTAINMENT_PLANES 8
#define PHYSICS_COLLISIONGROUP_FLUIDS 9
#define PHYSICS_COLLISIONGROUP_FLUIDS_DETAILED 10
#define PHYSICS_COLLISIONGROUP_NOCOLLISION 11
#define PHYSICS_COLLISIONGROUP_CLAW 12
#define _RESERVED_PHYSICS_COLLISIONGROUP_FLUIDS_WO_CONTAINMENT 13

#ifdef PROJECT_CLAW_PROTO
	#define PHYSICS_COLLISIONGROUP_TERRAIN 14
	#define PHYSICS_COLLISIONGROUP_DYNAMIC_NOTERRAIN 15
	#define PHYSICS_MAX_COLLISIONGROUPS 16
#else

	#define PHYSICS_MAX_COLLISIONGROUPS 14

#endif

#endif

