
#ifndef AREAMASKS_H
#define AREAMASKS_H

// ----------------------------------------------------
// area masks

#ifdef PROJECT_SHADOWGROUNDS

#define AREAMASK_DAMAGEAREA ((1<<0)|(1<<1)|(1<<2))
#define AREAMASK_INBUILDING ((1<<3))
#define AREAMASK_HOLEBELOW ((1<<4))
//#define AREAMASK_SCRIPTAREA ((1<<5)|(1<<6)|(1<<7))
#define AREAMASK_BREAKABLE ((1<<5))
#define AREAMASK_RESERVED_6 ((1<<6))
#define AREAMASK_RESERVED_7 ((1<<7))
//#define AREAMASK_SOUNDAREA  (256|512|1024)
//#define AREAMASK_AITURNBACK (2048|4096)
#define AREAMASK_OBSTACLE_UNHITTABLE ((1<<8))
#define AREAMASK_OBSTACLE_SEETHROUGH ((1<<9))
#define AREAMASK_OBSTACLE_MOVABLE ((1<<10))
#define AREAMASK_OBSTACLE_ROUNDED ((1<<11))
#define AREAMASK_OBSTACLE_BUILDINGWALL ((1<<12))
#define AREAMASK_MATERIAL ((1<<13)|(1<<14)|(1<<15))

// overlapping special masks...
#define AREAMASK_OBSTACLE_ALL ((1<<8)|(1<<9)|(1<<10)|(1<<11)|(1<<12))

#else

#define AREAMASK_MATERIAL ((1<<0)|(1<<1)|(1<<2)|(1<<3))
#define AREAMASK_INBUILDING ((1<<4))
#define AREAMASK_BREAKABLE ((1<<5))
#define AREAMASK_HOLEBELOW ((1<<6))
#define AREAMASK_RESERVED_7 ((1<<7))
#define AREAMASK_OBSTACLE_UNHITTABLE ((1<<8))
#define AREAMASK_OBSTACLE_SEETHROUGH ((1<<9))
#define AREAMASK_OBSTACLE_MOVABLE ((1<<10))
#define AREAMASK_OBSTACLE_ROUNDED ((1<<11))
#define AREAMASK_OBSTACLE_BUILDINGWALL ((1<<12))
#define AREAMASK_RESERVED_13 ((1<<13))
#define AREAMASK_RESERVED_14 ((1<<14))
#define AREAMASK_RESERVED_15 ((1<<15))

// overlapping special masks...
#define AREAMASK_OBSTACLE_ALL ((1<<8)|(1<<9)|(1<<10)|(1<<11)|(1<<12))

#endif


// ----------------------------------------------------
// damages

//#define AREASHIFT_DAMAGEAREA 0
//#define AREABITS_DAMAGEAREA 3

//#define AREAVALUE_DAMAGEAREA_NONE 0
//#define AREAVALUE_DAMAGEAREA_GENERIC (1<<AREASHIFT_DAMAGEAREA)
//#define AREAVALUE_DAMAGEAREA_POISON (2<<AREASHIFT_DAMAGEAREA)
//#define AREAVALUE_DAMAGEAREA_FIRE (3<<AREASHIFT_DAMAGEAREA)
//#define AREAVALUE_DAMAGEAREA_ACID (4<<AREASHIFT_DAMAGEAREA)
//#define AREAVALUE_DAMAGEAREA_ELECTRIC (5<<AREASHIFT_DAMAGEAREA)
//#define AREAVALUE_DAMAGEAREA_RADIOACTIVE (6<<AREASHIFT_DAMAGEAREA)
//#define AREAVALUE_DAMAGEAREA_FALL (7<<AREASHIFT_DAMAGEAREA)

// ----------------------------------------------------
// inside a building?

#ifdef PROJECT_SHADOWGROUNDS
#define AREASHIFT_INBUILDING 3
#else
#define AREASHIFT_INBUILDING 4
#endif
#define AREABITS_INBUILDING 1

#define AREAVALUE_INBUILDING_NO 0
#define AREAVALUE_INBUILDING_YES (1<<AREASHIFT_INBUILDING)

// ----------------------------------------------------
// is there a hole below the obstacle?

#ifdef PROJECT_SHADOWGROUNDS
#define AREASHIFT_HOLEBELOW 4
#else
#define AREASHIFT_HOLEBELOW 6
#endif
#define AREABITS_HOLEBELOW 1

#define AREAVALUE_HOLEBELOW_NO 0
#define AREAVALUE_HOLEBELOW_YES (1<<AREASHIFT_HOLEBELOW)

// ----------------------------------------------------
// is there a breakable obstacle here?

#define AREASHIFT_BREAKABLE 5
#define AREABITS_BREAKABLE 1

#define AREAVALUE_BREAKABLE_NO 0
#define AREAVALUE_BREAKABLE_YES (1<<AREASHIFT_BREAKABLE)

// ----------------------------------------------------
// scripting areas

/*
#define AREASHIFT_SCRIPTAREA 5
#define AREABITS_SCRIPTAREA 3

#define AREAVALUE_SCRIPTAREA_NONE 0
#define AREAVALUE_SCRIPTAREA_1 (1<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_2 (2<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_3 (3<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_4 (4<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_5 (5<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_6 (6<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_7 (7<<AREASHIFT_SCRIPTAREA)
*/
/*
#define AREAVALUE_SCRIPTAREA_8 (8<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_9 (9<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_10 (10<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_11 (11<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_12 (12<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_13 (13<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_14 (14<<AREASHIFT_SCRIPTAREA)
#define AREAVALUE_SCRIPTAREA_15 (15<<AREASHIFT_SCRIPTAREA)
*/

// ----------------------------------------------------
// sounds

/*
#define AREASHIFT_SOUNDAREA 8
#define AREABITS_SOUNDAREA 3

#define AREAVALUE_SOUNDAREA_NONE 0
#define AREAVALUE_SOUNDAREA_1 (1<<AREASHIFT_SOUNDAREA)
#define AREAVALUE_SOUNDAREA_2 (2<<AREASHIFT_SOUNDAREA)
#define AREAVALUE_SOUNDAREA_3 (3<<AREASHIFT_SOUNDAREA)
#define AREAVALUE_SOUNDAREA_4 (4<<AREASHIFT_SOUNDAREA)
#define AREAVALUE_SOUNDAREA_5 (5<<AREASHIFT_SOUNDAREA)
#define AREAVALUE_SOUNDAREA_6 (6<<AREASHIFT_SOUNDAREA)
#define AREAVALUE_SOUNDAREA_7 (7<<AREASHIFT_SOUNDAREA)
*/

// ----------------------------------------------------
// ai turnback

/*
#define AREASHIFT_AITURNBACK 11
#define AREABITS_AITURNBACK 2

#define AREAVALUE_AITURNBACK_NONE 0
#define AREAVALUE_AITURNBACK_HOSTILE (1<<AREASHIFT_AITURNBACK)
#define AREAVALUE_AITURNBACK_FRIENDLY (2<<AREASHIFT_AITURNBACK)
#define AREAVALUE_AITURNBACK_ALL (3<<AREASHIFT_AITURNBACK)
*/

// ----------------------------------------------------
// obstacles...

// WARNING: these values MUST equal to the ones defined in storm3d
// or unexpected behaviour will occur (see Storm3D_ObstacleMapDefs.h)

#define AREASHIFT_OBSTACLE_UNHITTABLE 8
#define AREABITS_OBSTACLE_UNHITTABLE 1
#define AREAVALUE_OBSTACLE_UNHITTABLE_NO 0
#define AREAVALUE_OBSTACLE_UNHITTABLE_YES (1<<AREASHIFT_OBSTACLE_UNHITTABLE)

#define AREASHIFT_OBSTACLE_SEETHROUGH 9
#define AREABITS_OBSTACLE_SEETHROUGH 1
#define AREAVALUE_OBSTACLE_SEETHROUGH_NO 0
#define AREAVALUE_OBSTACLE_SEETHROUGH_YES (1<<AREASHIFT_OBSTACLE_SEETHROUGH)

#define AREASHIFT_OBSTACLE_MOVABLE 10
#define AREABITS_OBSTACLE_MOVABLE 1
#define AREAVALUE_OBSTACLE_MOVABLE_NO 0
#define AREAVALUE_OBSTACLE_MOVABLE_YES (1<<AREASHIFT_OBSTACLE_MOVABLE)

#define AREASHIFT_OBSTACLE_ROUNDED 11
#define AREABITS_OBSTACLE_ROUNDED 1
#define AREAVALUE_OBSTACLE_ROUNDED_NO 0
#define AREAVALUE_OBSTACLE_ROUNDED_YES (1<<AREASHIFT_OBSTACLE_ROUNDED)

#define AREASHIFT_OBSTACLE_BUILDINGWALL 12
#define AREABITS_OBSTACLE_BUILDINGWALL 1
#define AREAVALUE_OBSTACLE_BUILDINGWALL_NO 0
#define AREAVALUE_OBSTACLE_BUILDINGWALL_YES (1<<AREASHIFT_OBSTACLE_BUILDINGWALL)

// special values for AREAMASK_OBSTACLE_ALL

// normal units
#define AREAVALUE_OBSTACLE_NORMAL_UNIT ( \
		AREAVALUE_OBSTACLE_SEETHROUGH_YES \
		| AREAVALUE_OBSTACLE_UNHITTABLE_YES \
		| AREAVALUE_OBSTACLE_MOVABLE_YES \
		| AREAVALUE_OBSTACLE_ROUNDED_NO \
		| AREAVALUE_OBSTACLE_BUILDINGWALL_NO \
	)

// doors
#define AREAVALUE_OBSTACLE_DOOR_UNIT ( \
		AREAVALUE_OBSTACLE_SEETHROUGH_NO \
		| AREAVALUE_OBSTACLE_UNHITTABLE_YES \
		| AREAVALUE_OBSTACLE_MOVABLE_YES \
		| AREAVALUE_OBSTACLE_ROUNDED_YES \
		| AREAVALUE_OBSTACLE_BUILDINGWALL_NO \
	)

// buildings
#define AREAVALUE_OBSTACLE_BUILDING ( \
		AREAVALUE_OBSTACLE_SEETHROUGH_NO \
		| AREAVALUE_OBSTACLE_UNHITTABLE_NO \
		| AREAVALUE_OBSTACLE_MOVABLE_NO \
		| AREAVALUE_OBSTACLE_ROUNDED_YES \
		| AREAVALUE_OBSTACLE_BUILDINGWALL_YES \
	)

// terrainobjects 
// (solid by default, | (or) with see/firethrough if necessary)
#define AREAVALUE_OBSTACLE_TERRAINOBJECT ( \
		AREAVALUE_OBSTACLE_SEETHROUGH_NO \
		| AREAVALUE_OBSTACLE_UNHITTABLE_NO \
		| AREAVALUE_OBSTACLE_MOVABLE_NO \
		| AREAVALUE_OBSTACLE_ROUNDED_YES \
		| AREAVALUE_OBSTACLE_BUILDINGWALL_NO \
	)


// ----------------------------------------------------

// materials

#ifdef PROJECT_SHADOWGROUNDS

#define AREASHIFT_MATERIAL 13
#define AREABITS_MATERIAL 3

#define AREAVALUE_MATERIAL_0
#define AREAVALUE_MATERIAL_1 (1<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_2 (2<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_3 (3<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_4 (4<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_5 (5<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_6 (6<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_7 (7<<AREASHIFT_MATERIAL)

#else

#define AREASHIFT_MATERIAL 0
#define AREABITS_MATERIAL 4

#define AREAVALUE_MATERIAL_0
#define AREAVALUE_MATERIAL_1 (1<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_2 (2<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_3 (3<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_4 (4<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_5 (5<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_6 (6<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_7 (7<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_8 (8<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_9 (9<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_10 (10<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_11 (11<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_12 (12<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_13 (13<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_14 (14<<AREASHIFT_MATERIAL)
#define AREAVALUE_MATERIAL_15 (15<<AREASHIFT_MATERIAL)

#endif

// ----------------------------------------------------

#endif

