
#ifndef DAMAGETYPES_H
#define DAMAGETYPES_H

#define DAMAGE_TYPE_INVALID -1

#define DAMAGE_TYPE_PROJECTILE 0
#define DAMAGE_TYPE_HEAT 1
#define DAMAGE_TYPE_ELECTRIC 2
#define DAMAGE_TYPE_STUN 3
// #define DAMAGE_TYPE_EXPLOSIVE 4 // a kind of projectile ?

#define DAMAGE_TYPES_AMOUNT 4

#endif
