
#ifndef HITSCRIPTDEFS_H
#define HITSCRIPTDEFS_H


/*
#define HITSCRIPT_NONE 0
#define HITSCRIPT_EXPLODE 1
//#define HITSCRIPT_CONTINUE_PATH 2
//#define HITSCRIPT_REVERSE_PATH 3
//#define HITSCRIPT_BOUNCE_PLANE_NORMAL 4
//#define HITSCRIPT_BOUNCE_PLANE_ANGLE 5
//#define HITSCRIPT_BOUNCE_HORIZONTAL 6
//#define HITSCRIPT_BOUNCE_RANDOM 7

#define HITSCRIPT_AMOUNT 8

namespace game
{
  extern char *hitScriptName[HITSCRIPT_AMOUNT];
}
*/


#endif

