
#ifndef PROJECTILEVISDEFS_H
#define PROJECTILEVISDEFS_H

/*
#define PROJECTILE_VIS_NONE 0
#define PROJECTILE_VIS_RED_RAY1 1
#define PROJECTILE_VIS_RED_RAY2 2
#define PROJECTILE_VIS_RED_PULSE1 3
#define PROJECTILE_VIS_RED_PULSE2 4
#define PROJECTILE_VIS_EXPLOSION1 5
#define PROJECTILE_VIS_FLAME1 6
#define PROJECTILE_VIS_SPARK1 7
//#define PROJECTILE_VIS_GREEN_RAY1 8
//#define PROJECTILE_VIS_GREEN_RAY2 9
//#define PROJECTILE_VIS_BLUE_PLASMA1 10
//#define PROJECTILE_VIS_BLUE_PLASMA2 11
#define PROJECTILE_VIS_EXPLOSION2 12
#define PROJECTILE_VIS_EXPLOSION3 13
#define PROJECTILE_VIS_ROCKET 14
#define PROJECTILE_VIS_GRENADE 15
#define PROJECTILE_VIS_DUST 16
#define PROJECTILE_VIS_SMOKE 17
#define PROJECTILE_VIS_RISINGSMOKE 18
#define PROJECTILE_VIS_SPARK2 19
#define PROJECTILE_VIS_GLOWFLARE 20
#define PROJECTILE_VIS_TIMEBOMB 21
#define PROJECTILE_VIS_TIMEBOMBARMED 22
#define PROJECTILE_VIS_MINE 23
#define PROJECTILE_VIS_MINEARMED 24
#define PROJECTILE_VIS_BULLET_STRIPE1 25
#define PROJECTILE_VIS_GAUSS 26

#define PROJECTILE_VIS_AMOUNT 27

namespace game
{
  extern char *projectileVisualName[PROJECTILE_VIS_AMOUNT];
}
*/

#endif

