
#ifndef GUI_CONFIGURATION_H
#define GUI_CONFIGURATION_H

#define GUI_BUILD_UPGRADE_WINDOW 1
#define GUI_BUILD_MAP_WINDOW 1
#define GUI_BUILD_LOG_WINDOW 1
#define GUI_BUILD_INGAME_GUI_TABS 1
#define GUI_BUILD_STORAGE_WINDOW 1
#define GUI_BUILD_INGAME_GUI 1
#define GUI_BUILD_WEAPON_SELECTION_WINDOW 1
#define GUI_BUILD_ELABORATE_HINT_MESSAGE 1
#define GUI_BUILD_COMBO_WINDOW 1

#endif

