package SGOptions;

use strict;

sub new
{
    my ($class) = @_;
    my $self = {
        DATA => {
            # Standard configuration settings
            _combobox("language","Language",
                      _language("English",0)),
            _combobox("resolution","Resolution",
                      _resolution(1920,1200),
                      _resolution(1920,1024),
                      _resolution(1600,1200),
                      _resolution(1600,1050),
                      _resolution(1600,1024),
                      _resolution(1280,1024),
                      _resolution(1280,800),
                      _resolution(1024,768),
                      _resolution(800,600),
                      _resolution(640,480)),
            _combobox("graphics_detail","Graphics Detail",
                      "Very High" => { extra_gamma_effects         => 1,
                                       fakeshadows_texture_quality => 100,
                                       gore_level                  => 100,
                                       high_quality_lightmap       => 1,
                                       lighting_level              => 100,
                                       lighting_texture_quality    => 100,
                                       particle_effects_level      => 100,
                                       render_glow                 => 1,
                                       better_glow_sampling        => 1,
                                       shadows_level               => 100,
                                       shadows_texture_quality     => 100,
                                       texture_detail_level        => 100,
                                       weather_effects             => 1,
                                       render_distortion           => 1,
                                       corpse_disappear_time       => 34,
                                       anisotrophy                 => 8,
                                       environment_animations      => 1,
                                       layer_effects_level         => 100,
                                       high_quality_video          => 1,
                                       menu_logo_video_enabled     => 1,
                                       procedural_fallback         => 0,
                                       antialias_samples           => 0,
                                       render_reflection           => 1, },
                      "High"      => { extra_gamma_effects         => 1,
                                       fakeshadows_texture_quality => 75,
                                       gore_level                  => 100,
                                       high_quality_lightmap       => 1,
                                       lighting_level              => 75,
                                       lighting_texture_quality    => 75,
                                       particle_effects_level      => 75,
                                       render_glow                 => 1,
                                       better_glow_sampling        => 0,
                                       shadows_level               => 75,
                                       shadows_texture_quality     => 75,
                                       texture_detail_level        => 100,
                                       weather_effects             => 1,
                                       render_distortion           => 1,
                                       corpse_disappear_time       => 34,
                                       anisotrophy                 => 4,
                                       environment_animations      => 1,
                                       layer_effects_level         => 75,
                                       high_quality_video          => 1,
                                       menu_logo_video_enabled     => 1,
                                       procedural_fallback         => 0,
                                       antialias_samples           => 0,
                                       render_reflection           => 0, },
                      "Medium"    => { extra_gamma_effects         => 1,
                                       fakeshadows_texture_quality => 50,
                                       gore_level                  => 50,
                                       high_quality_lightmap       => 1,
                                       lighting_level              => 50,
                                       lighting_texture_quality    => 50,
                                       particle_effects_level      => 50,
                                       render_glow                 => 1,
                                       better_glow_sampling        => 0,
                                       shadows_level               => 50,
                                       shadows_texture_quality     => 50,
                                       texture_detail_level        => 100,
                                       weather_effects             => 1,
                                       render_distortion           => 0,
                                       corpse_disappear_time       => 34,
                                       anisotrophy                 => 2,
                                       environment_animations      => 1,
                                       layer_effects_level         => 50,
                                       high_quality_video          => 1,
                                       menu_logo_video_enabled     => 1,
                                       procedural_fallback         => 0,
                                       antialias_samples           => 0, },
                      "Low"       => { extra_gamma_effects         => 1,
                                       fakeshadows_texture_quality => 25,
                                       gore_level                  => 25,
                                       high_quality_lightmap       => 0,
                                       lighting_level              => 25,
                                       lighting_texture_quality    => 25,
                                       particle_effects_level      => 25,
                                       render_glow                 => 0,
                                       better_glow_sampling        => 0,
                                       shadows_level               => 25,
                                       shadows_texture_quality     => 25,
                                       texture_detail_level        => 50,
                                       weather_effects             => 1,
                                       render_distortion           => 0,
                                       corpse_disappear_time       => 34,
                                       anisotrophy                 => 0,
                                       environment_animations      => 0,
                                       layer_effects_level         => 25,
                                       high_quality_video          => 0,
                                       menu_logo_video_enabled     => 0,
                                       procedural_fallback         => 0,
                                       antialias_samples           => 0,
                                       render_reflection           => 0, },
                      "Very Low"  => { extra_gamma_effects         => 0,
                                       fakeshadows_texture_quality => 0,
                                       gore_level                  => 0,
                                       high_quality_lightmap       => 0,
                                       lighting_level              => 0,
                                       lighting_texture_quality    => 0,
                                       particle_effects_level      => 0,
                                       render_glow                 => 0,
                                       better_glow_sampling        => 0,
                                       shadows_level               => 1,
                                       shadows_texture_quality     => 0,
                                       texture_detail_level        => 0,
                                       weather_effects             => 0,
                                       render_distortion           => 0,
                                       corpse_disappear_time       => 34,
                                       anisotrophy                 => 0,
                                       environment_animations      => 0,
                                       layer_effects_level         => 0,
                                       high_quality_video          => 0,
                                       menu_logo_video_enabled     => 0,
                                       procedural_fallback         => 1,
                                       antialias_samples           => 0,
                                       render_reflection           => 0, },
                      "Custom" => { }),
            _checkbox("enable_menu_videos","Enable Menu Videos",
                      { menu_video_enabled => 1 },
                      { menu_video_enabled => 0 }),
            _checkbox("vsync","Vertical Sync",
                      { render_use_vsync => 1 },
                      { render_use_vsync => 0 }),
						_checkbox("hrender", "Half Rendering",
											{ render_half_resolution => 1 },
											{ render_half_resolution => 0 }),
            _combobox("speaker_type","Speaker Type",
                      "Headphones"          => { sound_speaker_type => "headphones" },
                      "Mono Speakers"       => { sound_speaker_type => "mono" },
                      "Stereo Speakers"     => { sound_speaker_type => "stereo" },
                      "Quad Speakers"       => { sound_speaker_type => "quad" },
                      "Surround Speakers"   => { sound_speaker_type => "surround" },
                      "Multichannel (5.1+)" => { sound_speaker_type => "dolby" }),
            _combobox("mixing_rate","Mixing Rate",
                      "44100 Hz" => { sound_mixrate => 44100 },
                      "22050 Hz" => { sound_mixrate => 22050 }),
            _checkbox("hardware_3d","Hardware 3D",
                      { sound_use_hardware => 1 },
                      { sound_use_hardware => 0 }),
            _checkbox("eax","Use EAX",
                      { sound_use_eax => 1 },
                      { sound_use_eax => 0 }),
            _checkbox("sounds","Sounds Enabled",
                      { music_enabled  => 1,
                        sounds_enabled => 1,
                        speech_enabled => 1 },
                      { music_enabled  => 0,
                        sounds_enabled => 0,
                        speech_enabled => 0 }),
            # Advanced configuration settings
            _combobox("misc","Misc",
                      "Very High" => {
                          gore_level             => 100,
                          better_glow_sampling   => 1,
                          environment_animations => 1,
                          layer_effects_level    => 100,
                          procedural_fallback    => 0,
                      },
                      "High" => {
                          gore_level             => 100,
                          better_glow_sampling   => 0,
                          environment_animations => 1,
                          layer_effects_level    => 75,
                          procedural_fallback    => 0,
                      },
                      "Medium" => {
                          gore_level             => 50,
                          better_glow_sampling   => 0,
                          environment_animations => 1,
                          layer_effects_level    => 50,
                          procedural_fallback    => 0,
                      },
                      "Low" => {
                          gore_level             => 25,
                          better_glow_sampling   => 0,
                          environment_animations => 0,
                          layer_effects_level    => 25,
                          procedural_fallback    => 1,
                      },
                      "Very Low" => {
                          gore_level             => 0,
                          better_glow_sampling   => 0,
                          environment_animations => 0,
                          layer_effects_level    => 0,
                          procedural_fallback    => 1,
                      }),
            _combobox("anisotropic_filtering","Anisotropic Filtering",
                      "Disabled" => { anisotrophy => 0 },
                      "2"        => { anisotrophy => 2 },
                      "4"        => { anisotrophy => 4 },
                      "8"        => { anisotrophy => 8 }),
            _combobox("antialiasing","Antialiasing",
                      "Disabled" => { antialias_samples => 0 },
                      "2x"       => { antialias_samples => 2 },
                      "4x"       => { antialias_samples => 4 }),
            _combobox("ground_shadows_texture_quality","Ground shadows Texture Quality",
                      "Very High" => { fakeshadows_texture_quality => 100 },
                      "High"      => { fakeshadows_texture_quality => 75 },
                      "Medium"    => { fakeshadows_texture_quality => 50 },
                      "Low"       => { fakeshadows_texture_quality => 25 },
                      "Very Low"  => { fakeshadows_texture_quality => 0  }),
            _combobox("shadows_texture_quality","Shadows Texture Quality",
                      "Very High" => { shadows_texture_quality => 100 },
                      "High"      => { shadows_texture_quality => 75  },
                      "Medium"    => { shadows_texture_quality => 50  },
                      "Low"       => { shadows_texture_quality => 25  },
                      "Very Low"  => { shadows_texture_quality => 0   }),
            _checkbox("fullscreen","Full Screen",
                      { windowed => 0 },
                      { windowed => 1 }),
            _checkbox("high_quality_video","High Quality Video",
                      { high_quality_video      => 1,
                        menu_logo_video_enabled => 1, },
                      { high_quality_video      => 0,
                        menu_logo_video_enabled => 0, }),
            _checkbox("corpses_disappear","Disappearing Corpses",
                      { corpse_disappear_time   => 0  },
                      { corpse_disappear_time   => 34 }),
            _checkbox("distortion_effects","Distortion Effects",
                      { render_distortion => 1 },
                      { render_distortion => 0 }),
            _checkbox("extra_gamma_effects","Extra Gamma Effects",
                      { extra_gamma_effects => 1 },
                      { extra_gamma_effects => 0 }),
            _checkbox("high_quality_lightmap","High Quality Lightmap",
                      { high_quality_lightmap => 1 },
                      { high_quality_lightmap => 0 }),
            _combobox("lighting_level","Lighting Level",
                      "Very High" => { lighting_level => 100 },
                      "High"      => { lighting_level => 75  },
                      "Medium"    => { lighting_level => 50  },
                      "Low"       => { lighting_level => 25  },
                      "Very Low"  => { lighting_level => 0   }),
            _combobox("lighting_texture_quality","Lighting Texture Quality",
                      "Very High" => { lighting_texture_quality => 100 },
                      "High"      => { lighting_texture_quality => 75  },
                      "Medium"    => { lighting_texture_quality => 50  },
                      "Low"       => { lighting_texture_quality => 25  },
                      "Very Low"  => { lighting_texture_quality => 0   }),
            _combobox("weather_effects_level","Weather Effects Level",
                      "Very High" => { particle_effects_level => 100 },
                      "High"      => { particle_effects_level => 75  },
                      "Medium"    => { particle_effects_level => 50  },
                      "Low"       => { particle_effects_level => 25  },
                      "Very Low"  => { particle_effects_level => 0   }),
            _checkbox("render_glow","Render Glow",
                      { render_glow => 1 },
                      { render_glow => 0 }),
            _combobox("shadows_level","Shadows Level",
                      "Very High" => { shadows_level => 100 },
                      "High"      => { shadows_level => 75  },
                      "Medium"    => { shadows_level => 50  },
                      "Low"       => { shadows_level => 25  },
                      "Very Low"  => { shadows_level => 1   }),
            _combobox("texture_level","Texture Detail Level",
                      "High"      => { texture_detail_level => 100 },
                      "Low"       => { texture_detail_level => 50  },
                      "Very Low"  => { texture_detail_level => 0   }),
            _checkbox("weather_effects","Weather Effects",
                      { weather_effects => 1 },
                      { weather_effects => 0 }),
            _checkbox("reset_after_load","Reset After Load",
                      { reset_renderer_when_loaded => 1 },
                      { reset_renderer_when_loaded => 0 }),
            _combobox("physics_simlevel","Physics simulation level",
                      "Very High" => { physics_fluids_enabled      => 1,
                                       physics_max_fluid_particles => 300,
                                       physics_use_multithreading  => 1,
                                       physics_max_model_particles => 500, },
                      "High"      => { physics_fluids_enabled      => 1,
                                       physics_max_fluid_particles => 50,
                                       physics_use_multithreading  => 1,
                                       physics_max_model_particles => 300, },
                      "Medium"    => { physics_fluids_enabled      => 0,
                                       physics_use_multithreading  => 1,
                                       physics_max_model_particles => 80, },
                      "Low"       => { physics_fluids_enabled      => 0,
                                       physics_use_multithreading  => 0,
                                       physics_max_model_particles => 40, },
                      "Very Low"  => { physics_fluids_enabled      => 0,
                                       physics_use_multithreading  => 0,
                                       physics_max_model_particles => 0, }),
            _checkbox("use_ageia_hw","Use AGEIA PhysX hardware PPU",
                      { physics_use_hardware => 1 },
                      { physics_use_hardware => 0 }),
            # Unused
            # _checkbox("video_enabled","Enable Video",
            #          { video_enabled => 1 },
            #          { video_enabled => 0 }),
            
        },
    };
    bless($self,$class);
}

sub options
{
    my ($self) = @_;
    return keys %{$self->{DATA}};
}

sub option
{
    my ($self,$name) = @_;
    return $self->{DATA}->{$name} || die "No such option: $name";
}

sub _language
{
    my ($name,$id) = @_;
    return $name => {
        speech_language   => $id,
        subtitle_language => $id,
        menu_language     => $id,
    };
}

sub _resolution
{
    my ($width,$height) = @_;
    return $width."x".$height => {
        screen_bpp    => 32,
        screen_width  => $width,
        screen_height => $height,
    };
}

sub _combobox
{
    my ($name,$title,@items) = @_;
    return "$name" => {
        title => $title,
        items => [ @items ],
        type  => "combo",

    };
}

sub _checkbox
{
    my ($name,$title,$true,$false) = @_;
    return "$name" => {
        title => $title,
        items => [ true  => $true, false => $false, ],
        type => "check",
    };
}

1;
