
#ifndef OPTIONS_GUI_H
#define OPTIONS_GUI_H

#define DH_OPT_I_GUI_UNITS_POSITION 163
#define DH_OPT_I_GUI_RADAR_MODE 164

#define DH_OPT_I_GUI_TIP_MESSAGE_LEVEL 178

#define DH_OPT_I_CURSOR_RAYTRACE_OFFSET_Y 238

#define DH_OPT_B_GUI_RADAR_SHOW_ALL 259

#define DH_OPT_B_SHOW_SPLASH_SCREEN 305

#define DH_OPT_B_GUI_CURSOR_IS_RAYTRACING 312

#define DH_OPT_B_GUI_VISUALIZE_WINDOWS 328

#define DH_OPT_B_GUI_SHOW_CUSTOM_SURVIVAL_MISSIONS 333

#define DH_OPT_B_SHOW_SPLASH_SCREEN_ADVANCED 341

#define DH_OPT_B_USE_OLD_LOADGAMEMENU 353
#define DH_OPT_B_GUI_WIDESCREEN_FIXES 354
#define DH_OPT_B_SCOREWINDOW_NAME_INPUT 355

#define DH_OPT_B_GUI_CURSOR_RAYTRACE_HITS_UNITS 358
#define DH_OPT_F_GUI_MAP_AUTOZOOM 362

#endif

