
#ifndef OPTIONS_GRAPHICS_H
#define OPTIONS_GRAPHICS_H

#define DH_OPT_I_TEXTURE_DETAIL_LEVEL 24

#define DH_OPT_B_EXTRA_GAMMA_EFFECTS 64
#define DH_OPT_B_WEATHER_EFFECTS 65
#define DH_OPT_I_PARTICLE_EFFECTS_LEVEL 66
#define DH_OPT_B_GREEN_BLOOD 67
#define DH_OPT_I_GORE_LEVEL 68
#define DH_OPT_I_SHADOWS_LEVEL 69
#define DH_OPT_I_LIGHTING_LEVEL 70

#define DH_OPT_I_RENDER_MODE 77
#define DH_OPT_B_RENDER_SPOT_SHADOWS 78
#define DH_OPT_B_RENDER_GLOW 79
#define DH_OPT_B_RENDER_FAKELIGHTS 80
#define DH_OPT_B_RENDER_MODELS 81
#define DH_OPT_B_RENDER_TERRAINOBJECTS 82
#define DH_OPT_B_RENDER_HEIGHTMAP 83

#define DH_OPT_I_LIGHTING_TEXTURE_QUALITY 91
#define DH_OPT_I_SHADOWS_TEXTURE_QUALITY 92
#define DH_OPT_I_FAKESHADOWS_TEXTURE_QUALITY 93

#define DH_OPT_B_FREEZE_CAMERA_CULLING 94
#define DH_OPT_B_FREEZE_SPOT_CULLING 95

#define DH_OPT_B_RENDER_WIREFRAME 96
#define DH_OPT_B_RENDER_COLLISION 151

#define DH_OPT_B_HIGH_QUALITY_LIGHTMAP 165

#define DH_OPT_B_LIGHTMAP_FILTERING 171

#define DH_OPT_B_SHADER_GAMMA_EFFECTS 172

#define DH_OPT_B_RENDER_DECALS 173
#define DH_OPT_B_RENDER_SPOT_DEBUG 174
#define DH_OPT_B_RENDER_FAKESHADOW_DEBUG 175
#define DH_OPT_B_RENDER_GLOW_DEBUG 176
#define DH_OPT_B_RENDER_BONED 177
#define DH_OPT_B_RENDER_BLACK_AND_WHITE 205

#define DH_OPT_B_HIT_EFFECT_IMAGE 206

#define DH_OPT_B_ENVIRONMENT_ANIMATIONS 223
#define DH_OPT_B_RENDER_DISTORTION 224
#define DH_OPT_B_BETTER_GLOW_SAMPLING 228

#define DH_OPT_B_RENDER_CONE 229
#define DH_OPT_B_RENDER_PARTICLES 230
#define DH_OPT_B_RENDER_TERRAIN_TEXTURES 231
#define DH_OPT_B_RENDER_SMOOTHED_SHADOWS 232

#define DH_OPT_I_LAYER_EFFECTS_LEVEL 233
#define DH_OPT_I_CAMERA_CULLING_RATE 236
#define DH_OPT_B_PROCEDURAL_FALLBACK 242

#define DH_OPT_B_RESET_RENDERER_WHEN_LOADED 245
#define DH_OPT_B_RENDER_HALF_RESOLUTION 274
#define DH_OPT_B_RENDER_REFLECTION 291

#define DH_OPT_B_OCCLUSION_CULLING_ENABLED 294

// not to be used anymore. replaced by RENDER_MAX_POINTLIGHTS
//#define DH_OPT_I_RENDER_POINT_LIGHT_MAX_AMOUNT 310

#define DH_OPT_B_RENDER_PARTICLE_REFLECTION 323

#define DH_OPT_I_RENDER_MAX_POINTLIGHTS 329
#define DH_OPT_B_RENDER_SKY_BLOOM 344

#define DH_OPT_F_MAPVIEW_AMBIENT_LIGHTING 348

//#define DH_OPT_B_MAPVIEW_ENABLE_SPOTLIGHT 349

#define DH_OPT_I_MAPRENDER_SIZE_MULTIPLIER 360
#define DH_OPT_B_MAPRENDER_USE_USER_RESOLUTION 361

#endif

