
#ifndef OPTIONS_SOUNDS_H
#define OPTIONS_SOUNDS_H

#define DH_OPT_B_SOUNDS_ENABLED 117
#define DH_OPT_B_MUSIC_SHUFFLE 118
#define DH_OPT_I_MASTER_VOLUME 119
#define DH_OPT_B_MUSIC_ENABLED 120
#define DH_OPT_I_MUSIC_VOLUME 121
#define DH_OPT_B_SPEECH_ENABLED 122
#define DH_OPT_I_SPEECH_VOLUME 123
#define DH_OPT_B_FX_ENABLED 124
#define DH_OPT_I_FX_VOLUME 125

#define DH_OPT_I_SOUND_MIXRATE 138
#define DH_OPT_B_SOUND_USE_HARDWARE 139

#define DH_OPT_I_SOUND_SOFTWARE_CHANNELS 140
#define DH_OPT_I_SOUND_REQUIRED_HARDWARE_CHANNELS 141
#define DH_OPT_I_SOUND_MAX_HARDWARE_CHANNELS 142

#define DH_OPT_B_SOUND_USE_EAX 143
#define DH_OPT_S_SOUND_SPEAKER_TYPE 144

#define DH_OPT_B_SOUND_PRELOAD 162

#define DH_OPT_I_AMBIENT_VOLUME 346

#endif

