
#ifndef OPTIONS_VIDEO_H
#define OPTIONS_VIDEO_H

#define DH_OPT_B_VIDEO_ENABLED 22
#define DH_OPT_B_EXTERNAL_VIDEO_PLAYER 23
#define DH_OPT_B_MENU_VIDEO_ENABLED 225
#define DH_OPT_B_MENU_LOGO_VIDEO_ENABLED 240
#define DH_OPT_B_HIGH_QUALITY_VIDEO 241

#endif

