
#ifndef OPTIONS_PRECALC_H
#define OPTIONS_PRECALC_H

#define DH_OPT_B_FORCE_COVER_BIN_RECREATE 1
#define DH_OPT_B_AUTO_COVER_BIN_RECREATE 2

#define DH_OPT_B_FORCE_HIDE_BIN_RECREATE 9
#define DH_OPT_B_AUTO_HIDE_BIN_RECREATE 10

#define DH_OPT_B_FORCE_MODEL_BIN_RECREATE 45
#define DH_OPT_B_AUTO_MODEL_BIN_RECREATE 46

#define DH_OPT_B_FORCE_SCRIPT_PREPROCESS 47
#define DH_OPT_B_AUTO_SCRIPT_PREPROCESS 48
#define DH_OPT_S_SCRIPT_PREPROCESSOR 49

#define DH_OPT_S_SCRIPT_PREPROCESSOR_CHECK 54

#define DH_OPT_B_OLD_MODEL_BIN_RECREATE 86

#define DH_OPT_B_FORCE_OBSTACLE_BIN_RECREATE 169
#define DH_OPT_B_AUTO_OBSTACLE_BIN_RECREATE 170

#define DH_OPT_B_FORCE_PHYSICS_CACHE_RECREATE 284
#define DH_OPT_B_AUTO_PHYSICS_CACHE_RECREATE 285

#define DH_OPT_S_AST_PREPROCESSOR 306
#define DH_OPT_S_AST_PREPROCESSOR_CHECK 307
#define DH_OPT_B_FORCE_AST_PREPROCESS 308
#define DH_OPT_B_AUTO_AST_PREPROCESS 309

#endif

