
#ifndef OPTIONS_DEBUG_H
#define OPTIONS_DEBUG_H

#define DH_OPT_B_SHOW_TERRAIN_MEMORY_INFO 13
#define DH_OPT_B_SCRIPT_DEV_MODE 14

#define DH_OPT_B_DEBUG_CONSOLE_COMMANDS 19

#define DH_OPT_I_LOGLEVEL 42
#define DH_OPT_I_CONSOLE_LOGLEVEL 43
#define DH_OPT_I_RAISE_CONSOLE_LOGLEVEL 44

#define DH_OPT_B_SHOW_FPS 74
#define DH_OPT_B_SHOW_POLYS 75

#define DH_OPT_B_SHOW_DEBUG_DATA_VIEW 87
#define DH_OPT_I_DEBUG_DATA_VIEW_TYPE_MASK 88
#define DH_OPT_I_DEBUG_DATA_VIEW_RATE 89
#define DH_OPT_I_DEBUG_DATA_VIEW_ALPHA 90

#define DH_OPT_B_SHOW_DEBUG_RAYTRACES 152
#define DH_OPT_I_DEBUG_RAYTRACES_TYPE_MASK 153

#define DH_OPT_B_CONSOLE_HISTORY_SAVE 166

#define DH_OPT_B_MATERIAL_MISSING_WARNING 167
#define DH_OPT_B_SOUND_MISSING_WARNING 168

#define DH_OPT_B_CREATE_ERROR_LOG 237

#define DH_OPT_B_DEBUG_DATA_VIEW_PERF_STATS 243
#define DH_OPT_I_DEBUG_DATA_VIEW_PERF_STATS_RATE 244

#define DH_OPT_B_DEBUG_VISUALIZE_TRACKERS 304
#define DH_OPT_B_DEBUG_VISUALIZE_PROJECTILES 311

#define DH_OPT_B_DEBUG_VISUALIZE_UNITS 314
#define DH_OPT_B_DEBUG_VISUALIZE_UNITS_EXTENDED 315
#define DH_OPT_S_DEBUG_VISUALIZE_UNITS_VARIABLE 318
#define DH_OPT_S_DEBUG_VISUALIZE_UNITS_OF_TYPE 319
#define DH_OPT_B_MAGIC_SCREENSHOT 332
#define DH_OPT_B_DEBUG_VISUALIZE_PROJECTILES_EXTENDED 345

#define DH_OPT_B_DEBUG_VISUALIZE_POINTLIGHT_SHADOW_AREAS 349

#define DH_OPT_B_DEBUG_VISUALIZE_OBSTACLEMAP 352

#define DH_OPT_B_DEBUG_VISUALIZE_SELECTIONS 357

#define DH_OPT_B_SHOW_PLAYER_POS 359

#define DH_OPT_B_COLLECT_PERFORMANCE_STATS 363

#endif

