
#ifndef OPTIONS_CONTROLLERS_H
#define OPTIONS_CONTROLLERS_H

#define DH_OPT_B_MOUSE_ENABLED 25
#define DH_OPT_B_KEYBOARD_ENABLED 26
#define DH_OPT_B_JOYSTICK_ENABLED 27
#define DH_OPT_B_MOUSE_FORCE_GIVEN_BOUNDARY 28
#define DH_OPT_F_MOUSE_SENSITIVITY 29
#define DH_OPT_F_JOYSTICK_SENSITIVY 235

// NOTE: these must ne incremental in id values:
#define DH_OPT_S_CONTROLLER_SCRIPT_1 97
#define DH_OPT_S_CONTROLLER_SCRIPT_2 98
#define DH_OPT_S_CONTROLLER_SCRIPT_3 99
#define DH_OPT_S_CONTROLLER_SCRIPT_4 100
#define DH_OPT_S_CONTROLLER_SCRIPT_5 101
#define DH_OPT_S_CONTROLLER_SCRIPT_6 102
#define DH_OPT_S_CONTROLLER_SCRIPT_7 103
#define DH_OPT_S_CONTROLLER_SCRIPT_8 104
#define DH_OPT_S_CONTROLLER_SCRIPT_9 105
#define DH_OPT_S_CONTROLLER_SCRIPT_10 106
#define DH_OPT_S_CONTROLLER_SCRIPT_11 107
#define DH_OPT_S_CONTROLLER_SCRIPT_12 108
#define DH_OPT_S_CONTROLLER_SCRIPT_13 109
#define DH_OPT_S_CONTROLLER_SCRIPT_14 110
#define DH_OPT_S_CONTROLLER_SCRIPT_15 111
#define DH_OPT_S_CONTROLLER_SCRIPT_16 112

#define DH_OPT_B_CONTROLLER_MULTIPLE_INPUT_DEVICES_ENABLED 335

#define DH_OPT_I_CONTROLLER_PLAYER1_MOUSE_ID 336
#define DH_OPT_I_CONTROLLER_PLAYER2_MOUSE_ID 337
#define DH_OPT_I_CONTROLLER_PLAYER3_MOUSE_ID 338
#define DH_OPT_I_CONTROLLER_PLAYER4_MOUSE_ID 339

#ifdef PROJECT_CLAW_PROTO
#define DH_OPT_I_CLAW_CONTROL_TYPE 325
#define DH_OPT_I_CLAW_AIM_MODE 369
#endif

#endif

