
#ifndef OPTIONS_DISPLAY_H
#define OPTIONS_DISPLAY_H

#define DH_OPT_F_GAMMA 57
#define DH_OPT_F_BRIGHTNESS 58
#define DH_OPT_F_CONTRAST 59
#define DH_OPT_F_RED_CORRECTION 60
#define DH_OPT_F_GREEN_CORRECTION 61
#define DH_OPT_F_BLUE_CORRECTION 62
#define DH_OPT_B_CALIBRATE_GAMMA 63

#define DH_OPT_I_SCREEN_WIDTH 132
#define DH_OPT_I_SCREEN_HEIGHT 133
#define DH_OPT_I_SCREEN_BPP 134
#define DH_OPT_B_WINDOWED 135
#define DH_OPT_B_MAXIMIZE_WINDOW 136

#define DH_OPT_I_RENDER_MAX_FPS 145
#define DH_OPT_B_RENDER_USE_VSYNC 150

#define DH_OPT_I_ANTIALIAS_SAMPLES 226
#define DH_OPT_I_ANISOTROPHY 227

#define DH_OPT_B_WINDOW_TITLEBAR 250

#define DH_OPT_B_USE_REFERENCE_DRIVER 350
#define DH_OPT_B_RENDER_ONLY_WHEN_REQUESTED 351

#endif

