
#ifndef OPTIONS_PLAYERS_H
#define OPTIONS_PLAYERS_H

// NOTE: all of these player options must be in increments of one for each player 
// (1st - 4th)

#define DH_OPT_B_1ST_PLAYER_ENABLED 30
#define DH_OPT_B_2ND_PLAYER_ENABLED 31
#define DH_OPT_B_3RD_PLAYER_ENABLED 32
#define DH_OPT_B_4TH_PLAYER_ENABLED 33

#define DH_OPT_S_1ST_PLAYER_KEYBINDS 34
#define DH_OPT_S_2ND_PLAYER_KEYBINDS 35
#define DH_OPT_S_3RD_PLAYER_KEYBINDS 36
#define DH_OPT_S_4TH_PLAYER_KEYBINDS 37

#define DH_OPT_B_1ST_PLAYER_HAS_CURSOR 38
#define DH_OPT_B_2ND_PLAYER_HAS_CURSOR 39
#define DH_OPT_B_3RD_PLAYER_HAS_CURSOR 40
#define DH_OPT_B_4TH_PLAYER_HAS_CURSOR 41

#define DH_OPT_I_1ST_PLAYER_CONTROL_SCHEME 50
#define DH_OPT_I_2ND_PLAYER_CONTROL_SCHEME 51
#define DH_OPT_I_3RD_PLAYER_CONTROL_SCHEME 52
#define DH_OPT_I_4TH_PLAYER_CONTROL_SCHEME 53

#endif

