
#ifndef OPTIONS_CHEATS_H
#define OPTIONS_CHEATS_H

#define DH_OPT_B_SHOW_ALL_UNITS 6
#define DH_OPT_B_SHOW_ENEMY_TACTICAL 7
#define DH_OPT_B_NO_CAMERA_BOUNDARIES 8

#define DH_OPT_B_ALLOW_SIDE_SWAP 20
#define DH_OPT_B_SHOW_PATHS 21
#define DH_OPT_B_AUTOAIM_HORIZONTAL 115
#define DH_OPT_B_AUTOAIM_VERTICAL 116

#define DH_OPT_B_PLAYER_DEMO_INVULNERABILITY 149

#endif

