
#ifndef OPTIONS_TACTICAL_H
#define OPTIONS_TACTICAL_H

#define DH_OPT_B_SHOW_TACTICAL_TEXT 3
#define DH_OPT_B_MENU_TWO_CLICK 4
#define DH_OPT_B_MENU_AUTOPAUSE 5

#define DH_OPT_B_TARGET_BASED_WEAPON_CHOOSE 15
#define DH_OPT_B_TARGETING_STOPS 16
#define DH_OPT_B_DOUBLE_CLICK_MOVE_FAST 17
#define DH_OPT_B_HOSTILE_SIGHTED_AUTOPAUSE 18

#endif

