//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define IDD_DIALOG1                     100
#define IDD_TERRAIN                     101
#define IDD_MENU                        102
#define IDD_OPTIONS                     103
#define IDR_MENU                        104
#define IDD_OBJECTS                     107
#define IDD_PARTICLES                   108
#define IDD_RENDER                      109
#define IDD_HMAP                        111
#define IDD_TEXTURELAYERS               112
#define IDD_TERRAINTEXTURING            112
#define IDD_SCENE                       113
#define IDD_COLORPICK                   114
#define IDD_PARTICLES2                  115
#define IDD_ITEMTYPE                    116
#define IDD_SPHEREEMITTER               117
#define IDD_PARTICLE                    118
#define IDD_DIALOG2                     119
#define IDD_COLORPICKER                 120
#define IDD_EMITTER                     121
#define IDD_PTEX                        122
#define IDD_SPRAY_EMITTER               123
#define IDD_CLOUD_EMITTER               124
#define IDD_POINT_ARRAY                 125
#define IDD_NAME                        126
#define IDD_SHADOWS                     127
#define IDD_PSYS                        128
#define IDD_SELECTION                   129
#define IDB_BITMAP1                     131
#define IDD_SINGLE_SEL                  133
#define IDD_PS_HELP                     134
#define IDR_POPUP                       135
#define IDD_BUILDINGS                   135
#define IDD_EXPORT                      136
#define IDD_UNITS                       137
#define IDD_DECORATORS                  138
#define IDD_UNIT_PROPERTIES             139
#define IDD_LIGHTS                      140
#define IDD_GROUPSAVE                   141
#define IDD_STRING                      142
#define IDI_ICON1                       143
#define IDI_ICON2                       144
#define IDD_DIALOG3                     145
#define IDD_NEWMISSION                  145
#define IDD_MULTIEXPORT                 146
#define IDC_RADIO1                      1001
#define IDC_MENU_TERRAIN                1001
#define IDC_TERRAIN_MODE_SPLAT          1001
#define IDC_ALL                         1001
#define IDC_OBJECT_DRAG                 1002
#define IDC_RADIO2                      1002
#define IDC_BUTTON1                     1002
#define IDC_MENU_OBJECTS                1002
#define IDC_NEW_TEMPLATE                1002
#define IDC_PARTICLE                    1002
#define IDC_NEW_PS                      1002
#define IDC_P_TEXTURE_LOAD              1002
#define IDC_P_COLOR                     1002
#define IDC_EMITTER_EXTENDED            1002
#define IDC_PA_MODEL                    1002
#define IDC_E_MORE                      1002
#define IDC_SE_HIDE                     1002
#define IDC_PSYS_HIDE                   1002
#define IDC_LOAD_LEGACY                 1002
#define IDC_OPTIMIZE_TEXTURES           1002
#define IDC_UNIT_OPEN                   1002
#define IDC_LIGHT_TEXTURE               1002
#define IDC_CALCULATE_COLOR             1002
#define IDC_NEWMISSION                  1002
#define IDC_RADIO3                      1003
#define IDC_MENU_UNITS                  1003
#define IDC_FOG_COLORB                  1003
#define IDC_OBJECT_REMOVE               1003
#define IDC_DELETE_TEMPLATE             1003
#define IDC_DELETE_PS                   1003
#define IDC_P_ALPHA                     1003
#define IDC_MENU_BUILDINGS              1003
#define IDC_POINT_DELETE                1003
#define IDC_TERRAIN_MODE_HEIGHTS        1003
#define IDC_EASY                        1003
#define IDC_LIGHT_CONE_TEXTURE          1003
#define IDC_CALCULATE_LIGHTMAP          1003
#define IDC_RADIO4                      1004
#define IDC_BUTTON3                     1004
#define IDC_MENU_SCRIPTS                1004
#define IDC_HMAP_TEXTURELAYERS          1004
#define IDC_AMBIENT_COLORB              1004
#define IDC_SAVE_TEMPLATE               1004
#define IDC_LOAD_PS                     1004
#define IDC_P_SIZE                      1004
#define IDC_MENU_UNIT                   1004
#define IDC_HARD                        1004
#define IDC_LIGHT_COLOR                 1004
#define IDC_RADIO5                      1005
#define IDC_CHECK1                      1005
#define IDC_MENU_IMPORT                 1005
#define IDC_SELECTION_MODE              1005
#define IDC_MENU_PARTICLES              1005
#define IDC_LOAD_TEMPLATE               1005
#define IDC_LOOPING                     1005
#define IDC_SAVE_PS                     1005
#define IDC_EMITTER_EMITRATE            1005
#define IDC_CE_RANDOM_DIRECTION         1005
#define IDC_OBJECT_FIRETHROUGH          1005
#define IDC_HIDE_ROOF                   1005
#define IDC_SHADOW_COLORB               1005
#define IDC_POINT_RESET                 1005
#define IDC_SCRIPT_ONLY                 1005
#define IDC_RENDER_MODELS               1005
#define IDC_HEIGHT_PICK                 1005
#define IDC_LIGHT_MODEL                 1005
#define IDC_CHECK2                      1006
#define IDC_MENU_SCENE                  1006
#define IDC_DRAG_MODE                   1006
#define IDC_REMOVE_ENTRY                1006
#define IDC_EMITTER_DIRECTION           1006
#define IDC_SHOW_DOOR                   1006
#define IDC_POINT_INSERT                1006
#define IDC_LIGHT_ROTATE                1006
#define IDC_FOG_ENABLED                 1006
#define IDC_TERRAIN_MODE_HEIGHTS2       1006
#define IDC_TERRAIN_MODE_LIGHTMAP       1006
#define IDC_CHECK3                      1007
#define IDC_MODE_CANCEL                 1007
#define IDC_EMITTER_UPDATE              1007
#define IDC_ADD_ENTRY                   1007
#define IDC_MENU_DECORATORS             1007
#define IDC_RENDER_HEIGHTMAP            1007
#define IDC_CUT_TERRAIN                 1007
#define IDC_MENU_LIGHTS                 1007
#define IDC_LIGHT_FADE                  1007
#define IDC_GROUP_TOOL_FILTER_BACK      1007
#define IDC_RENDER_GLOW                 1008
#define IDC_LIGHT_COLOR_GUESS           1008
#define IDC_GROUP_TOOL_FILTER_GROUND    1008
#define IDC_BUTTON4                     1009
#define IDC_FOG_COLOR                   1009
#define IDC_GROUP_TOOL_FILTER_DECAL     1009
#define IDC_LIGHT_MODEL_ERASE           1010
#define IDC_FOG_ID_ADD                  1010
#define IDC_GROUP_TOOL_FILTER_PROP      1010
#define IDC_FOG_CAMERA                  1011
#define IDC_GROUP_TOOL_FILTER_DYNAMIC   1011
#define IDC_RENDER_DISTORTION           1012
#define IDC_GROUP_TOOL_FILTER_STATIC    1012
#define IDC_SAVE                        1013
#define IDC_MENU_SAVE                   1013
#define IDC_GROUP_TOOL_FILTER_NOCOLLISION 1013
#define IDC_MENU_UPDATE                 1014
#define IDC_GROUP_TOOL_FILTER_HELPER    1014
#define ID_OPEN_HMAP                    1015
#define IDC_MENU_RELOAD                 1015
#define IDC_GROUP_TOOL_FILTER_INVERT    1015
#define IDC_HMAP_HEIGHT1                1016
#define IDC_MENU_RELOAD2                1016
#define IDC_MENU_RESET                  1016
#define IDC_GROUP_TOOL_FILTER_MAINGROUP 1016
#define IDC_HMAP_HEIGHT2                1017
#define IDC_GROUP_TOOL_FILTER_SUBGROUP  1017
#define IDC_GROUP_TOOL_FILTER_MODELS    1017
#define IDC_HMAP_TYPE                   1018
#define IDC_HMAP_HEIGHT3                1018
#define IDC_GROUP_TOOL_FILTER_LIGHTS    1018
#define IDC_WIDTH                       1019
#define IDC_HMAP_SDIVIDER               1019
#define IDC_GROUP_TOOL_FILTER_LIGHTS2   1019
#define IDC_GROUP_TOOL_FILTER_UNITS     1019
#define IDC_HEIGHT                      1020
#define IDC_HMAP_SSTART                 1020
#define IDC_HMAP_OK                     1021
#define ID_OPEN_DETAIL1                 1021
#define IDC_HMAP_WIDTH                  1022
#define IDC_HMAP_HEIGHT                 1023
#define ID_OPEN_DETAIL2                 1024
#define IDC_HMAP_TEXTURES               1025
#define IDC_HMAP_ADD                    1026
#define IDC_HMAP_REMOVE                 1027
#define IDC_HMAP_DREPEAT1               1028
#define IDC_HMAP_DREPEAT2               1029
#define IDC_LAYER1_TEXTURE              1029
#define IDC_HMAP_ALT                    1030
#define IDC_LAYER1_EXPLOSION            1030
#define IDC_LAYER1_SLOPE                1031
#define IDC_LAYER3_TEXTURE              1032
#define IDC_LAYER3_EXPLOSION            1033
#define IDC_LAYER3_SLOPE                1034
#define IDC_LAYER2_TEXTURE              1035
#define IDC_LAYER2_EXPLOSION            1036
#define IDC_LAYER2_SLOPE                1037
#define IDC_LAYER4_TEXTURE              1038
#define IDC_LAYER4_EXPLOSION            1039
#define IDC_LAYER4_SLOPE                1040
#define IDC_TL_OK                       1041
#define IDC_SUN_X                       1042
#define IDC_SUN_Y                       1043
#define IDC_LAYER5_TEXTURE              1044
#define IDC_SUN_Z                       1044
#define IDC_LAYER5_EXPLOSION            1045
#define IDC_FOG_SRANGE                  1045
#define IDC_LAYER5_SLOPE                1046
#define IDC_FOG_ERANGE                  1046
#define IDC_SHADOW_TEXTURE              1047
#define ID_OPEN_BGMODEL                 1047
#define IDC_CAMERA_RANGE                1048
#define IDC_SUN_COLORB                  1050
#define IDC_FOG_ENABLE                  1051
#define IDC_COLOR_R                     1052
#define IDC_AMBIENT_ENABLE              1052
#define IDC_COLOR_G                     1053
#define IDC_COLOR_B                     1054
#define IDC_CPICK_OK                    1055
#define IDC_OBJECT_MODELS               1058
#define IDC_EDIT1                       1059
#define IDC_P_TEX_FILE_NAME             1059
#define IDC_CE_MIN_SPEED                1059
#define IDC_MAX_PARTICLES               1059
#define IDC_COLOR_RT                    1059
#define IDC_WATERHEIGHT_1               1059
#define IDC_OBJECT_GROUP_LIST           1059
#define IDC_EDIT2                       1060
#define IDC_HMAP_SMOOTH                 1060
#define IDC_CE_MAX_SPEED                1060
#define IDC_COLOR_GT                    1060
#define IDC_WATERHEIGHT_2               1060
#define IDC_OBJECT_VALUE                1060
#define IDC_MULTIEXPORT_LOG             1060
#define IDC_EMITTERPOS_Y                1061
#define IDC_P_NUM_FRAMES                1061
#define IDC_CE_BOX_MIN_Z                1061
#define IDC_COLOR_BT                    1061
#define IDC_CLICK_MODE                  1062
#define IDC_EMITTERPOS_Z                1062
#define IDC_CE_BOX_MAX_Z                1062
#define IDC_OBJECT_CLICK                1062
#define IDC_OBJECT_INSERT               1062
#define IDC_OBJECT_ADD                  1063
#define IDC_EMITTERDIR_X                1063
#define IDC_P_FPS                       1063
#define IDC_CE_SPHERE_OUTER             1063
#define IDC_MODE_OK                     1064
#define IDC_EMITTERDIR_Y                1064
#define IDC_P_START_FRAME               1064
#define IDC_CE_CYL_HEIGHT               1064
#define IDC_TEMPLATE_COMBO              1065
#define IDC_EMITTERDIR_Z                1065
#define IDC_ITEM_COMBO                  1066
#define IDC_MINVELOCITY_X               1066
#define IDC_OBJECT_AMOUNT               1066
#define IDC_ITEM_LIST                   1067
#define IDC_MINVELOCITY_Y               1067
#define IDC_OBJECT_TYPE                 1068
#define IDC_ADD_ITEM                    1068
#define IDC_MINVELOCITY_Z               1068
#define IDC_COMBO2                      1068
#define IDC_UNIT_SIDE                   1068
#define IDC_UNIT_LAYOUT                 1068
#define IDC_LIGHT_GROUP_E               1068
#define IDC_OBJECT_HEIGHT               1069
#define IDC_REMOVE_ITEM                 1069
#define IDC_ITEMTYPE_COMBO              1069
#define IDC_MAXVELOCITY_X               1069
#define IDC_OBJECT_RADIUS               1070
#define IDC_EDIT_ITEM                   1070
#define IDC_MAXVELOCITY_Y               1070
#define IDC_OBJECT_XSIZE                1070
#define IDC_OBJECT_PROPERTIES           1071
#define IDC_CLONE_ITEM                  1071
#define IDC_MAXVELOCITY_Z               1071
#define IDC_OBJECT_ZSIZE                1071
#define IDC_STATIC_TYPE                 1072
#define IDC_INNERRADIUS_EDIT            1072
#define IDC_STATIC_HEIGHT               1073
#define IDC_EMITTERPOS_X                1073
#define IDC_STATIC_TYPE2                1073
#define IDC_STATIC_RADIUS               1074
#define IDC_PHASE                       1074
#define IDC_FALL_TYPE                   1074
#define IDC_STATIC_METERS               1075
#define IDC_MAXTOTALVELOCITY            1075
#define IDC_STATIC_METERS2              1076
#define IDC_VELOCITYFACTOR              1076
#define IDC_VISUALIZE_COLLISION         1077
#define IDC_STATIC_RADIUS2              1077
#define IDC_STATIC_TYPE3                1077
#define IDC_RED_SLIDER                  1078
#define IDC_STATIC_METERS3              1078
#define IDC_EXPLOSION_OBJECT            1078
#define IDC_CYCLE                       1079
#define IDC_RED_EDIT                    1079
#define IDC_STATIC_METERS4              1079
#define IDC_PERIOID                     1080
#define IDC_GREEN_SLIDER                1080
#define IDC_STATIC_TYPE4                1080
#define IDC_EMITTERMAXPARTICLES         1081
#define IDC_GREEN_EDIT                  1081
#define IDC_EXPLOSION_EFFECT            1081
#define IDC_PARTICLESPERSEC             1082
#define IDC_BLUE_SLIDER                 1082
#define IDC_STATIC_TYPE5                1082
#define IDC_OUTERRADIUS_EDIT            1083
#define IDC_BLUE_EDIT                   1083
#define IDC_EXPLOSION_PROJECTILE        1083
#define IDC_COLOR_RECT                  1084
#define IDC_STATIC_TYPE6                1084
#define IDC_STATIC_TYPE7                1086
#define IDC_EXPLOSION_SCRIPT            1087
#define IDC_ENTRY_LIST                  1088
#define IDC_STATIC_TYPE8                1088
#define IDC_NEW_ENTRY                   1089
#define IDC_MATERIAL                    1089
#define IDC_DELETE_ENTRY                1090
#define IDC_STATIC_TYPE9                1090
#define IDC_PS_LIST                     1091
#define IDC_EXPLOSION_SOUND             1091
#define IDC_ENTRY_COMBO                 1092
#define IDC_STATIC_TYPE10               1092
#define IDC_EDIT_ENTRY                  1093
#define IDC_E_MIN_EMIT_TIME             1093
#define IDC_ANIMATION                   1093
#define IDC_E_MAX_EMIT_TIME             1094
#define IDC_E_POSGEN                    1095
#define IDC_P_MIN_ANGLE                 1096
#define IDC_P_MAX_ANGLE                 1097
#define IDC_P_MIN_ANGLE_CHANGE          1098
#define IDC_OBJECT_ROTATE               1099
#define IDC_P_MAX_ANGLE_CHANGE          1099
#define IDC_E_MAX_PARTICLES             1100
#define IDC_OBJECT_ILLUMINATION         1100
#define IDC_E_FOREVER                   1101
#define IDC_E_DIE_AFTER_EMISSION        1101
#define IDC_OBJECT_GROUPTOOL            1101
#define IDC_ADD_PS                      1102
#define IDC_P_MIN_LIFE                  1102
#define IDC_P_ANIM_TYPE                 1103
#define IDC_P_MAX_LIFE                  1103
#define IDC_P_ALPHA_TYPE                1104
#define IDC_E_GRAVITY                   1104
#define IDC_P_MIN_SPIN                  1104
#define IDC_P_FRAME_WIDTH               1105
#define IDC_P_MAX_SPIN                  1105
#define IDC_P_FRAME_HEIGHT              1106
#define IDC_P_GRAVITY_MULTIPLIER        1106
#define IDC_PS_COMBO                    1108
#define IDC_P_TEXTURE                   1109
#define IDC_PARTICLE_UPDATE             1110
#define IDC_P_HIDE                      1110
#define IDC_E_NAME                      1111
#define IDC_P_DRAG_FACTOR               1111
#define IDC_SYS_MAX_PARTICLES           1112
#define IDC_P_BOUNCE                    1112
#define IDC_SYS_GRAVITY                 1113
#define IDC_ENTRY_TYPE                  1114
#define IDC_SE_SPREAD1                  1115
#define IDC_SE_SPREAD2                  1116
#define IDC_SE_MIN_SPEED                1117
#define IDC_CE_SHAPE                    1117
#define IDC_SE_MAX_SPEED                1118
#define IDC_CE_BOX_MIN_X                1118
#define IDC_CE_BOX_MIN_Y                1119
#define IDC_CE_BOX_MAX_X                1120
#define IDC_CE_BOX_MAX_Y                1121
#define IDC_CE_SPHERE_INNER             1122
#define IDC_CE_CYL_RADIUS               1123
#define IDC_PA_RANGE_START              1123
#define IDC_PA_RANGE_END                1124
#define IDC_CE_DIRECTION_X              1124
#define IDC_CE_DIRECTION_Y              1125
#define IDC_P_DRAG_BY_VELOCITY          1125
#define IDC_PA_MIN_SPEED                1125
#define IDC_CE_DIRECTION_Z              1126
#define IDC_P_DRAG_BY_SIZE              1126
#define IDC_PA_MAX_SPEED                1126
#define IDC_P_DRAW_STYLE                1127
#define IDC_P_NAME                      1128
#define IDC_P_COLLISION_TYPE            1129
#define IDC_P_RENAME                    1130
#define IDC_E_RENAME                    1131
#define IDC_NAME_EDIT                   1132
#define IDC_E_HIDE                      1133
#define IDC_P_TEXDLG_HIDE               1134
#define IDC_PA_HIDE                     1135
#define IDC_SLIDER1                     1136
#define IDC_SHADOW_DARKNESS             1136
#define IDC_SLIDER2                     1137
#define IDC_CE_HIDE                     1137
#define IDC_SHADOW_LENGTH               1137
#define IDC_LIGHT_HEIGHT                1138
#define IDC_LIGHT_ANGLE                 1139
#define IDC_LIGHT_BLINK_SPEED           1140
#define IDC_LIGHT_ROTATE_SPEED          1141
#define IDC_SUN_XANGLE                  1141
#define IDC_LIGHT_FADE_SPEED            1142
#define IDC_SUN_STRENGTH                1142
#define IDC_LIGHT_PLANE_R               1143
#define IDC_LIGHT_PLANE_G               1144
#define IDC_LIGHT_PLANE_B               1145
#define IDC_LIGHT_PLANE_Y               1146
#define IDC_LIGHT_ROTATE_RANGE          1147
#define IDC_LIST3                       1148
#define IDC_LIGHT_CONE_MUL              1148
#define IDC_LIST4                       1149
#define IDC_LIGHT_STRENGTH              1149
#define IDC_BUTTON5                     1150
#define IDC_LIGHT_SOURCE_HEIGHT2        1150
#define IDC_BUTTON6                     1151
#define IDC_LIGHT_SMOOTHNESS            1151
#define IDC_BUTTON7                     1152
#define IDC_BUTTON8                     1153
#define IDC_BUTTON9                     1154
#define IDC_BUTTON10                    1155
#define IDC_COMBO1                      1156
#define IDC_SELECTION1                  1157
#define IDC_UNIT_MAIN                   1157
#define IDC_TERRAIN_TEXTURE2            1157
#define IDC_LIGHTMAP_QUALITY            1157
#define IDC_GROUP_SUBGROUP              1157
#define IDC_PHYSICS_MASS                1157
#define IDC_SELECTION2                  1158
#define IDC_UNIT_CONFIGURATION          1158
#define IDC_BOTTOM_TEXTURE              1158
#define IDC_UNIT_ALERTED                1159
#define IDC_UNIT_HIT                    1160
#define IDC_UNIT_HITMISS                1161
#define IDC_UNIT_NOISE                  1162
#define IDC_UNIT_EXECUTE                1163
#define IDC_TREE1                       1164
#define IDC_UNIT_SPECIAL                1164
#define IDC_SELECTED_TEMPLATE           1165
#define IDC_UNIT_POINTED                1165
#define IDC_SEL                         1167
#define IDC_EXPORT_TEMPLATE             1169
#define IDC_IMPORT_TEMPLATE             1170
#define IDC_BUILDING_ADD                1171
#define IDC_BUILDING_REMOVE             1172
#define IDC_BUILDING_MODELS             1173
#define IDC_BUILDING_INSERTMODE         1174
#define IDC_BUILDING_REMOVEMODE         1175
#define IDC_MISSION_NAMES               1176
#define IDC_EXPORT                      1177
#define IDC_EXPORT2                     1178
#define IDC_BUTTON2                     1178
#define IDC_WATERMODEL_1                1178
#define IDC_UNIT_DELETE                 1178
#define IDC_LIGHT_DELETE                1178
#define IDC_SUN_UPDATE                  1178
#define IDC_EXPORT3                     1179
#define IDC_BUTTON11                    1179
#define IDC_WATERMODEL_2                1179
#define IDC_UNIT_LIST                   1179
#define IDC_BUTTON12                    1180
#define IDC_UNIT_HELPERS                1180
#define IDC_BUTTON13                    1181
#define IDC_UNIT_SPOTTED                1181
#define IDC_TEXTURE_DETAIL              1182
#define IDC_GENERATE                    1183
#define IDC_TERRAIN_TEXTURE1            1184
#define IDC_SPLAT_TEXTURE               1185
#define IDC_SPLAT_RADIUS                1186
#define IDC_EDIT_RADIUS                 1186
#define IDC_SPLAT_STRENGTH              1187
#define IDC_EDIT_STRENGTH               1187
#define IDC_UNIT_TYPE                   1188
#define IDC_UNIT_TYPE_PRIMARY           1188
#define IDC_OBJECT_GROUP                1189
#define IDC_UNIT_TYPE_SECONDARY         1189
#define IDC_OBJECT_SUBGROUP             1190
#define IDC_FREEZE_CAMERA_CULLING       1190
#define IDC_HEIGHT_MODE                 1190
#define IDC_RENDER_MODE                 1191
#define IDC_HEIGHT_SHAPE                1191
#define IDC_OBJECT_GROUP_GROUP          1191
#define IDC_FORCE_WIREFRAME             1192
#define IDC_OBJECT_GROUP_SUBGROUP       1192
#define IDC_APPLY_CAMERA_RANGE          1193
#define IDC_FORCE_GAME_CAMERA           1194
#define IDC_UNIT_PROPERTIES             1194
#define IDC_UNIT_DATANAME               1195
#define IDC_FORCE_COLLISION             1195
#define IDC_UNIT_DATA                   1196
#define IDC_LIGHTMAP_FILTER             1196
#define IDC_LIGHT_GROUP_ENABLE          1197
#define IDC_REFLECTION                  1197
#define IDC_LIGHT_VISUALIZATION         1198
#define IDC_FORCE_GRID                  1198
#define IDC_LIGHT_DETAIL                1199
#define IDC_FORCE_FOLD                  1199
#define IDC_LIGHT_GROUP_C               1200
#define IDC_SHOW_UNITS                  1200
#define IDC_LIGHT_PRIORITY              1201
#define IDC_SHOW_TRIGGERS               1201
#define IDC_LIGHT_SHADOWS               1202
#define IDC_SHOW_HELPERS                1202
#define IDC_LIGHT_RANGE                 1203
#define IDC_SHOW_INCOMPLETE             1203
#define IDC_LIGHT_FOV                   1204
#define IDC_SHOW_STATIC                 1204
#define IDC_LIGHT_TYPE                  1205
#define IDC_SHOW_DYNAMIC                1205
#define IDC_SHOW_NOCOLLISION            1206
#define IDC_LIGHT_GROUP_C2              1206
#define IDC_LIGHT_MAX_AMOUNT            1206
#define IDC_LIGHT_BLINK                 1207
#define IDC_SHOW_INCOMPLETE2            1207
#define IDC_SHOW_EDITORONLY             1207
#define IDC_LIGHT_SHADOW                1209
#define IDC_LIGHT_CONE_TEXTURE_ERASE    1210
#define IDC_UNIT_DATA_DEFAULTVALUE      1211
#define IDC_LIGHT_LIGHTMAPPED           1212
#define IDC_LIGHTMAP_AREA               1213
#define IDC_LIGHT_POINTLIGHT            1213
#define IDC_LIGHT_SYNC                  1214
#define IDC_EXPLOSION_HP                1215
#define IDC_LIGHT_BUILDING              1215
#define IDC_SUN_YANGLE                  1216
#define IDC_GROUP_GROUP                 1217
#define IDC_GROUP_NAME                  1218
#define IDC_OBJECT_BREAK_TEX            1219
#define IDC_FOG_END                     1220
#define IDC_FOG_START                   1221
#define IDC_FOG_ID                      1222
#define IDC_STRING                      1223
#define IDC_ANISO                       1224
#define IDC_SMOOTH_SHADOWS              1225
#define IDC_LIGHT_OFFSET                1225
#define IDC_ACTIVE_MOD                  1226
#define IDC_PHYSICS_TYPE                1227
#define IDC_PHYSICS_TYPE2               1228
#define IDC_PHYSICS_MATERIAL            1228
#define IDC_PHYSICS_MATERIAL2           1229
#define IDC_PHYSICS_DURABILITY          1229
#define IDC_OBJECT_ID                   1230
#define IDC_EDIT3                       1231
#define IDC_LONKERO                     1231
#define IDC_MISSIONFOLDER               1232
#define IDC_LIGHT_LIGHTINGMODEL_TYPE    1233
#define IDC_LIGHT_LIGHTINGMODEL_FADE    1234
#define IDC_NEWMISSION_NAME             1235
#define IDC_NEWMISSION_OK               1236
#define IDC_MULTIEXPORT_LIST            1237
#define IDC_MULTIEXPORT_LIGHTMAP        1238
#define IDC_MULTIEXPORT_OK              1239
#define ID_FILE_SAVEAS                  40003
#define ID_FILE__SAVEAS                 40003
#define ID_FILE_QUIT                    40004
#define ID_FILE__QUIT                   40004
#define ID_VIEW_TERRAINOPTIONS          40005
#define ID_VIEW_OBJECTOPTIONS           40006
#define ID_VIEW_UNITOPTIONS             40007
#define ID_VIEW_SCRIPTOPTIONS           40008
#define ID_VIEW_IMPORTOPTIONS           40009
#define ID_EDITORS_ITEMEDITOR           40010
#define ID_EDITORS_UNITEDITOR           40011
#define ID_SETTINGS_A_A                 40012
#define ID_SETTINGS_A_B                 40013
#define ID_SETTINGS_B_B                 40014
#define ID_SETTINGS_B_BB                40015
#define ID_FILE__NEW                    40016
#define ID_FILE__OPEN                   40017
#define ID_FILE_EXPORTTOGAME            40018
#define IDM_NEW                         40023
#define IDM_DELETE                      40024
#define IDM_EDIT                        40025
#define IDM_SAVE                        40026
#define ID_Menu                         40027
#define ID_FILE_MULTIEXPORT             40028

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         40029
#define _APS_NEXT_CONTROL_VALUE         1240
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
