//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by viewer.rc
//
#define IDD_RENDER                      101
#define IDD_MAIN                        102
#define IDI_ICON1                       103
#define IDD_ITEMS                       104
#define IDD_SPRAY_PARTICLE_SYSTEM       105
#define IDD_PARTICLE_SYSTEM_SELECT      106
#define IDD_FLOAT_TRACK                 107
#define IDD_VECTOR_TRACK                108
#define IDD_FORCE_SELECT                109
#define IDD_GRAVITY                     110
#define IDD_DRAG                        111
#define IDD_RENAME                      112
#define IDD_COLORPICK                   114
#define IDD_POINT_ARRAY_PARTICLE_SYSTEM 115
#define IDD_WIND                        116
#define IDD_MODEL_PARTICLE_SYSTEM       117
#define IDD_SIDEGRAVITY                 118
#define IDC_GEOMETRY                    1001
#define IDC_NEW_EFFECT                  1001
#define IDC_BONES                       1002
#define IDC_LOAD_EFFECT                 1002
#define IDC_CLEAR_MODELS                1003
#define IDC_ANIMATIONS                  1004
#define IDC_PARTICLE_SYSTEMS            1004
#define IDC_BASE                        1005
#define IDC_ENABLE                      1005
#define IDC_ATTACH                      1006
#define IDC_SAVE_EFFECT                 1006
#define IDC_SAVE_EFFECT2                1007
#define IDC_SAVE_EFFECT_AS              1007
#define IDC_PLAY                        1008
#define IDC_LOOP                        1009
#define IDC_ADD                         1010
#define IDC_STOP                        1012
#define IDC_DRAW_BONES                  1013
#define IDC_LOAD                        1014
#define IDC_LOAD_MODEL                  1014
#define IDC_SAVE                        1015
#define IDC_LOAD_MODEL2                 1015
#define IDC_VIEWER_CONFIG               1015
#define IDC_BLEND                       1016
#define IDC_DISABLE                     1016
#define IDC_INSERT                      1017
#define IDC_INSERT_PARTICLE_SYSTEM      1017
#define IDC_REMOVE                      1018
#define IDC_HELPERS                     1018
#define IDC_REMOVE_PARTICLE_SYSTEM      1018
#define IDC_COLOR                       1020
#define IDC_ITEMS                       1020
#define IDC_ITEM_REMOVE                 1021
#define IDC_ITEM_INSERT                 1022
#define IDC_EMIT_RATE                   1023
#define IDC_EMIT_START                  1024
#define IDC_EMIT_STOP                   1025
#define IDC_EMITTER_POSITION_X          1026
#define IDC_EMITTER_POSITION_Z          1027
#define IDC_EMITTER_POSITION_Y          1028
#define IDC_SCALE_X                     1029
#define IDC_EMITTER_VARIATION_X2        1029
#define IDC_SCALE_Y                     1030
#define IDC_EMITTER_VARIATION_Z2        1030
#define IDC_SCALE_Z                     1031
#define IDC_EMITTER_VARIATION_Y2        1031
#define IDC_LAUNCH_SPEED                1032
#define IDC_LAUNCH_SPEED_VAR            1033
#define IDC_PARTICLE_COLOR              1034
#define IDC_PARTICLE_SIZE               1035
#define IDC_PARTICLE_ALPHA              1036
#define IDC_DEFAULT_DIRECTION_X         1037
#define IDC_PARTICLE_LIFE               1038
#define IDC_PARTICLE_LIFE_VAR           1039
#define IDC_PARTICLE_ANGLE              1040
#define IDC_PARTICLE_ANGLE_VAR          1041
#define IDC_PARTICLE_SPIN               1042
#define IDC_PARTICLE_SPIN_VAR           1043
#define IDC_PARTICLE_TEXTURE            1044
#define IDC_UPDATE                      1045
#define IDC_PARTICLE_SYSTEM_TYPE        1046
#define IDC_DEFAULT_DIRECTION_Y         1046
#define IDC_EDIT_PARTICLE_SYSTEM        1047
#define IDC_DEFAULT_DIRECTION_Z         1047
#define IDC_KEYS                        1048
#define IDC_ROTATION_X                  1048
#define IDC_VALUE                       1049
#define IDC_ROTATION_Y                  1049
#define IDC_ROTATION_Z                  1050
#define IDC_VALUE_X                     1051
#define IDC_EMIT_DARKENING              1051
#define IDC_COLOR_R                     1052
#define IDC_TIME                        1052
#define IDC_EMITTER_VARIATION_X         1052
#define IDC_COLOR_G                     1053
#define IDC_ADD_KEY                     1053
#define IDC_VALUE_Y                     1053
#define IDC_EMITTER_VARIATION_Z         1053
#define IDC_COLOR_B                     1054
#define IDC_REMOVE_KEY                  1054
#define IDC_ANIMATION_FRAME_COUNT       1054
#define IDC_VALUE_Z                     1054
#define IDC_CPICK_OK                    1055
#define IDC_TEXTURE_SUB_DIV_U           1055
#define IDC_TEXTURE_SUB_DIV_V           1056
#define IDC_EMITTER_VARIATION_Y         1057
#define IDC_SPREAD1                     1058
#define IDC_SPREAD2                     1059
#define IDC_ADD_KEYV                    1059
#define IDC_TEXTURE_ALPHA_TYPE          1060
#define IDC_REMOVE_KEYV                 1060
#define IDC_LAUNCH_DIRECTION            1061
#define IDC_MAX_PARTICLES               1062
#define IDC_DIE_AFTER_EMISSION          1063
#define IDC_VELOCITY_INHERITANCE_FACTOR 1064
#define IDC_PARTICLE_TEXTURE_FILE       1065
#define IDC_ANIMATION_START_FRAME       1066
#define IDC_ANIMATION_START_FRAME_VAR   1067
#define IDC_ANIMATION_FPS               1068
#define IDC_ELEMENT_TYPE                1069
#define IDC_ANIMATION_TYPE              1070
#define IDC_KEYSV                       1071
#define IDC_TIMEV                       1072
#define IDC_RELOAD2                     1073
#define IDC_RELOAD                      1073
#define IDC_FORCES                      1074
#define IDC_INSERT_FORCE                1075
#define IDC_REMOVE_FORCE                1076
#define IDC_EDIT_FORCE                  1077
#define IDC_MODEL                       1078
#define IDC_MODEL_FILE                  1079
#define IDC_DIRECTION_NORMALS           1080
#define IDC_FIRST_VERTEX                1081
#define IDC_PARTICLE_MODEL              1081
#define IDC_LAST_VERTEX                 1082
#define IDC_FORCE_TYPE                  1082
#define IDC_PARTICLE_MODEL_FILE         1082
#define IDC_GRAVITY                     1083
#define IDC_POSITIONS_BETWEEN_VERTICES  1083
#define IDC_PLANE_POSITIONS             1084
#define IDC_DRAG                        1086
#define IDC_RENAME                      1087
#define IDC_SPIRAL                      1087
#define IDC_NAME                        1088
#define IDC_SPIRAL_SPEED                1088
#define IDC_SLOW_MOTION                 1089
#define IDC_SHOW_EMITTERS               1090
#define IDC_EFFECT_UP                   1091
#define IDC_EFFECT_DOWN                 1092
#define IDC_EDIT1                       1093
#define IDC_PARTICLE_Y_SLOW_FACTOR      1093
#define IDC_PARTICLE_XZ_SLOW_FACTOR     1094
#define IDC_WIND_EFFECT_FACTOR          1095
#define IDC_PARTICLE_SLOW_FACTOR        1095
#define IDC_PARTICLE_ANGLE1_1           1097
#define IDC_PARTICLE_ANGLE1_2           1098
#define IDC_PARTICLE_ANGLE2_1           1099
#define IDC_PARTICLE_ANGLE2_2           1100
#define IDC_DISTORTION                  1102
#define IDC_GLOW                        1103
#define IDC_OUTSIDE                     1103
#define IDC_FORCE_AMBIENT               1104
#define IDC_OBSTACLE_HEIGHT             1104
#define IDC_TIME_FACTOR                 1105
#define IDC_HEIGHT_HEIGHT               1105
#define IDC_COLLISION                   1106
#define IDC_OUTSIDE_FADE                1106
#define IDC_FLUIDVIS                    1106
#define IDC_FLUID_STUFF                 1106
#define IDC_UNIT_COLLISION              1107
#define IDC_UPWARD                      1107
#define IDC_PHYSICS_TYPE                1114
#define IDC_FLUID_STATIC_RESTITUTION    1115
#define IDC_FLUID_STATIC_ADHESION       1116
#define IDC_FLUID_DYNAMIC_RESTITUTION   1117
#define IDC_FLUID_DYNAMIC_ADHESION      1118
#define IDC_FLUID_DAMPING               1119
#define IDC_FLUID_STIFFNESS             1120
#define IDC_SOUND_MATERIAL              1120
#define IDC_FLUID_VISCOSITY             1121
#define IDC_FLUID_KERNEL_RADIUS_MULTIPLIER 1122
#define IDC_FLUID_REST_PARTICLES_PER_METER 1123
#define IDC_FLUID_REST_DENSITY          1124
#define IDC_FLUID_MOTION_LIMIT          1125
#define IDC_FLUID_PACKET_SIZE_MULTIPLIER 1127
#define IDC_FLUID_PACKET_SIZE_MULTIPLIER2 1128
#define IDC_FLUID_MAX_EMITTER_AMOUNT    1128
#define IDC_FLUID_DETAIL_COLLISION_GROUP 1129
#define IDC_SIDEGRAVITY                 1131
#define IDC_CHECK1                      1132
#define IDC_PHYSICS                     1132

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1133
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
