
#ifndef NET_NETFLAGS_H
#define NET_NETFLAGS_H

// Copyright(C) Jukka Kokkonen, 2002

#define NET_NETMODE_FLAG_NONBLOCKING 1
#define NET_NETMODE_FLAG_NOSIGNAL 2
#define NET_NETMODE_FLAG_NOEXCEPTIONS 4

#endif


